-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Products Table
create table if not exists products (
  id text primary key, -- Keeping text to match current UUIDs generated by frontend, or we can switch to uuid default gen_random_uuid()
  name text not null,
  description text,
  price numeric,
  compare_at_price numeric,
  image text,
  images jsonb default '[]'::jsonb,
  category text,
  tags text[],
  sku text,
  stock integer default 0,
  track_inventory boolean default true,
  has_variants boolean default false,
  variant_options jsonb default '[]'::jsonb,
  variants jsonb default '[]'::jsonb,
  seo jsonb default '{}'::jsonb,
  status text default 'active',
  template text,
  allow_customization boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Pages Table
create table if not exists pages (
  id text primary key,
  title text not null,
  slug text not null unique,
  type text default 'custom',
  content text, -- Deprecated but kept for compatibility
  blocks jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

-- Media Assets Table
create table if not exists media_assets (
  id text primary key,
  url text not null,
  name text not null,
  type text not null,
  size numeric,
  created_at timestamptz default now()
);

-- Campaigns Table
create table if not exists campaigns (
  id text primary key,
  name text not null,
  type text not null,
  status text default 'draft',
  subject text,
  content text,
  audience text,
  scheduled_for timestamptz,
  sent_at timestamptz,
  stats jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

-- Store Config Table (Single Row)
create table if not exists store_config (
  id integer primary key default 1,
  name text default 'Nexus Store',
  currency text default 'USD',
  header_style text default 'canvas',
  hero_style text default 'impact',
  product_card_style text default 'classic',
  footer_style text default 'columns',
  scrollbar_style text default 'native',
  primary_color text default '#000000',
  logo_url text,
  logo_height integer default 32,
  updated_at timestamptz default now(),
  constraint single_row check (id = 1)
);

-- Insert default config if not exists
insert into store_config (id, name)
values (1, 'Nexus Store')
on conflict (id) do nothing;

-- Enable Row Level Security (RLS)
alter table products enable row level security;
alter table pages enable row level security;
alter table media_assets enable row level security;
alter table campaigns enable row level security;
alter table store_config enable row level security;

-- Create Policies (Public Read / Anon Write for Demo Purposes)
-- IN PRODUCTION: You should restrict Write access to authenticated users only.
create policy "Public Read Products" on products for select using (true);
create policy "Public Write Products" on products for insert with check (true);
create policy "Public Update Products" on products for update using (true);
create policy "Public Delete Products" on products for delete using (true);

create policy "Public Read Pages" on pages for select using (true);
create policy "Public Write Pages" on pages for insert with check (true);
create policy "Public Update Pages" on pages for update using (true);
create policy "Public Delete Pages" on pages for delete using (true);

create policy "Public Read Media" on media_assets for select using (true);
create policy "Public Write Media" on media_assets for insert with check (true);
create policy "Public Update Media" on media_assets for update using (true);
create policy "Public Delete Media" on media_assets for delete using (true);

create policy "Public Read Campaigns" on campaigns for select using (true);
create policy "Public Write Campaigns" on campaigns for insert with check (true);
create policy "Public Update Campaigns" on campaigns for update using (true);
create policy "Public Delete Campaigns" on campaigns for delete using (true);

create policy "Public Read Config" on store_config for select using (true);
create policy "Public Update Config" on store_config for update using (true);
